# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ATraslationClass
                                 A QGIS plugin
 A plugin with translation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-23
        copyright            : (C) 2025 by fdobad
        email                : fbadilla@ing.uchile.cl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ATraslationClass class from file ATraslationClass.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .a_translation_module import ATraslationClass
    return ATraslationClass(iface)
