# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AClassName
                                 A QGIS plugin
 A plugin description
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-05-23
        copyright            : (C) 2025 by fdobad
        email                : fbadilla@ing.uchile.cl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'fdobad'
__date__ = '2025-05-23'
__copyright__ = '(C) 2025 by fdobad'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AClassName class from file AClassName.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .a_module import AClassNamePlugin
    return AClassNamePlugin()
